document.getElementById("changeWhite").onclick = function(){
  document.getElementById("output1").style.color = '#101010';
  document.getElementById("output2").style.color = '#101010';
  document.getElementById("output3").style.color = '#101010';
  document.getElementById("output4").style.color = '#101010';
  document.getElementById("output5").style.color = '#101010';
  document.getElementById("output6").style.color = '#101010';
  document.getElementById("output7").style.color = '#101010';
  document.getElementById("dark").style.backgroundColor = '#efeff4';
  dark.style.transition = "all 1s";
  output1.style.transition = "all 1s";
  output2.style.transition = "all 1s";
  output3.style.transition = "all 1s";
  output4.style.transition = "all 1s";
  output5.style.transition = "all 1s";
  output6.style.transition = "all 1s";}

document.getElementById("changeBlack").onclick = function(){
  document.getElementById("output1").style.color = '#f0eef1';
  document.getElementById("output2").style.color = '#f0eef1';
  document.getElementById("output3").style.color = '#f0eef1';
  document.getElementById("output4").style.color = '#f0eef1';
  document.getElementById("output5").style.color = '#f0eef1';
  document.getElementById("output6").style.color = '#f0eef1';
  document.getElementById("output7").style.color = '#f0eef1';
  document.getElementById("dark").style.backgroundColor = '#101010';
  dark.style.transition = "all 1s";
  output1.style.transition = "all 1s";
  output2.style.transition = "all 1s";
  output3.style.transition = "all 1s";
  output4.style.transition = "all 1s";
  output5.style.transition = "all 1s";
  output6.style.transition = "all 1s";}
